from enum import Enum


class PropertyType(str, Enum):
    CHECKBOX = "checkbox"
    CREATED_BY = "created_by"
    CREATED_TIME = "created_time"
    DATE = "date"
    EMAIL = "email"
    FILES = "files"
    FORMULA = "formula"
    LAST_EDITED_BY = "last_edited_by"
    LAST_EDITED_TIME = "last_edited_time"
    MULTI_SELECT = "multi_select"
    NUMBER = "number"
    PEOPLE = "people"
    PHONE_NUMBER = "phone_number"
    RELATION = "relation"
    RICH_TEXT = "rich_text"
    ROLLUP = "rollup"
    SELECT = "select"
    STATUS = "status"
    TITLE = "title"
    URL = "url"
    UNIQUE_ID = "unique_id"
    VERIFICATION = "verification"


class NumberFormat(str, Enum):
    ARGENTINE_PESO = "argentine_peso"
    BAHT = "baht"
    AUSTRALIAN_DOLLAR = "australian_dollar"
    CANADIAN_DOLLAR = "canadian_dollar"
    CHILEAN_PESO = "chilean_peso"
    COLOMBIAN_PESO = "colombian_peso"
    DANISH_KRONE = "danish_krone"
    DIRHAM = "dirham"
    DOLLAR = "dollar"
    EURO = "euro"
    FORINT = "forint"
    FRANC = "franc"
    HONG_KONG_DOLLAR = "hong_kong_dollar"
    KORUNA = "koruna"
    KRONA = "krona"
    LEU = "leu"
    LIRA = "lira"
    MEXICAN_PESO = "mexican_peso"
    NEW_TAIWAN_DOLLAR = "new_taiwan_dollar"
    NEW_ZEALAND_DOLLAR = "new_zealand_dollar"
    NORWEGIAN_KRONE = "norwegian_krone"
    NUMBER = "number"
    NUMBER_WITH_COMMAS = "number_with_commas"
    PERCENT = "percent"
    PHILIPPINE_PESO = "philippine_peso"
    POUND = "pound"
    PERUVIAN_SOL = "peruvian_sol"
    RAND = "rand"
    REAL = "real"
    RINGGIT = "ringgit"
    RIYAL = "riyal"
    RUBLE = "ruble"
    RUPEE = "rupee"
    RUPIAH = "rupiah"
    SHEKEL = "shekel"
    SINGAPORE_DOLLAR = "singapore_dollar"
    URUGUAYAN_PESO = "uruguayan_peso"
    YEN = "yen"
    YUAN = "yuan"
    WON = "won"
    ZLOTY = "zloty"


class RollupFunction(str, Enum):
    AVERAGE = "average"
    CHECKED = "checked"
    COUNT = "count"
    COUNT_PER_GROUP = "count_per_group"
    COUNT_VALUES = "count_values"
    DATE_RANGE = "date_range"
    EARLIEST_DATE = "earliest_date"
    EMPTY = "empty"
    LATEST_DATE = "latest_date"
    MAX = "max"
    MEDIAN = "median"
    MIN = "min"
    NOT_EMPTY = "not_empty"
    PERCENT_CHECKED = "percent_checked"
    PERCENT_EMPTY = "percent_empty"
    PERCENT_NOT_EMPTY = "percent_not_empty"
    PERCENT_PER_GROUP = "percent_per_group"
    PERCENT_UNCHECKED = "percent_unchecked"
    RANGE = "range"
    SHOW_ORIGINAL = "show_original"
    SHOW_UNIQUE = "show_unique"
    SUM = "sum"
    UNCHECKED = "unchecked"
    UNIQUE = "unique"


class FormulaValueType(str, Enum):
    BOOLEAN = "boolean"
    DATE = "date"
    NUMBER = "number"
    STRING = "string"


class RollupValueType(str, Enum):
    ARRAY = "array"
    DATE = "date"
    INCOMPLETE = "incomplete"
    NUMBER = "number"
    UNSUPPORTED = "unsupported"
