from importlib import import_module
from typing import TYPE_CHECKING

from pydantic import PydanticUndefinedAnnotation

# noinspection PyUnresolvedReferences
_dynamic_imports = {
    # objects
    "NotionObjectId": (__spec__.parent, ".object"),
    "NotionObjectType": (__spec__.parent, ".object"),
    "NotionObjectIdWrapper": (__spec__.parent, ".object"),
    # types
    "NotionEmptyDict": (__spec__.parent, ".types"),
    "Color": (__spec__.parent, ".types"),
    "BackgroundColor": (__spec__.parent, ".types"),
    "NotionEquation": (__spec__.parent, ".types"),
    "NotionUrlWrapper": (__spec__.parent, ".types"),
    "NotionDatetime": (__spec__.parent, ".types"),
    "NotionDate": (__spec__.parent, ".types"),
    # file
    "FileType": (__spec__.parent, ".file"),
    "HostedFileObject": (__spec__.parent, ".file"),
    "ExternalFileObject": (__spec__.parent, ".file"),
    "HostedFile": (__spec__.parent, ".file"),
    "HostedFileWithName": (__spec__.parent, ".file"),
    "ExternalFile": (__spec__.parent, ".file"),
    "ExternalFileWithName": (__spec__.parent, ".file"),
    "NotionFile": (__spec__.parent, ".file"),
    "NotionFileWithName": (__spec__.parent, ".file"),
    # emoji
    "EmojiType": (__spec__.parent, ".emoji"),
    "CustomEmojiObject": (__spec__.parent, ".emoji"),
    "SingleEmoji": (__spec__.parent, ".emoji"),
    "CustomEmoji": (__spec__.parent, ".emoji"),
    "NotionEmoji": (__spec__.parent, ".emoji"),
    # user
    "UserType": (__spec__.parent, ".user"),
    "BotOwnerType": (__spec__.parent, ".user"),
    "WorkspaceBotOwner": (__spec__.parent, ".user"),
    "UserBotOwner": (__spec__.parent, ".user"),
    "BotOwner": (__spec__.parent, ".user"),
    "Bot": (__spec__.parent, ".user"),
    "Person": (__spec__.parent, ".user"),
    "PersonUser": (__spec__.parent, ".user"),
    "BotUser": (__spec__.parent, ".user"),
    "UserRef": (__spec__.parent, ".user"),
    "NotionUser": (__spec__.parent, ".user"),
    # parent
    "ParentType": (__spec__.parent, ".parent"),
    "DatabaseParent": (__spec__.parent, ".parent"),
    "PageParent": (__spec__.parent, ".parent"),
    "BlockParent": (__spec__.parent, ".parent"),
    "NotionParent": (__spec__.parent, ".parent"),
    "WorkspaceParent": (__spec__.parent, ".parent"),
    # rich text
    "RichTextType": (__spec__.parent, ".rich_text.types"),
    "MentionType": (__spec__.parent, ".rich_text.types"),
    "TemplateMentionType": (__spec__.parent, ".rich_text.types"),
    "Annotations": (__spec__.parent, ".rich_text.common"),
    "Text": (__spec__.parent, ".rich_text.common"),
    "Equation": (__spec__.parent, ".rich_text.common"),
    "DatabaseMention": (__spec__.parent, ".rich_text.common"),
    "DateMention": (__spec__.parent, ".rich_text.common"),
    "LinkPreviewMention": (__spec__.parent, ".rich_text.common"),
    "PageMention": (__spec__.parent, ".rich_text.common"),
    "TemplateMentionDate": (__spec__.parent, ".rich_text.common"),
    "TemplateMentionUser": (__spec__.parent, ".rich_text.common"),
    "TemplateMention": (__spec__.parent, ".rich_text.common"),
    "RxUserMention": (__spec__.parent, ".rich_text.rx"),
    "TxUserMention": (__spec__.parent, ".rich_text.tx"),
    "RxMention": (__spec__.parent, ".rich_text.rx"),
    "TxMention": (__spec__.parent, ".rich_text.tx"),
    "RxTextRichText": (__spec__.parent, ".rich_text.rx"),
    "RxMentionRichText": (__spec__.parent, ".rich_text.rx"),
    "RxEquationRichText": (__spec__.parent, ".rich_text.rx"),
    "TxTextRichText": (__spec__.parent, ".rich_text.tx"),
    "TxMentionRichText": (__spec__.parent, ".rich_text.tx"),
    "TxEquationRichText": (__spec__.parent, ".rich_text.tx"),
    "RxRichText": (__spec__.parent, ".rich_text.rx"),
    "TxRichText": (__spec__.parent, ".rich_text.tx"),
    # block
    "BlockType": (__spec__.parent, ".block.types"),
    "ProgrammingLanguage": (__spec__.parent, ".block.types"),
    "SyncedFrom": (__spec__.parent, ".block.common"),
    "DuplicateSynced": (__spec__.parent, ".block.common"),
    "TableOfContents": (__spec__.parent, ".block.common"),
    "ChildDatabase": (__spec__.parent, ".block.rx"),
    "ChildPage": (__spec__.parent, ".block.rx"),
    "RxBlock": (__spec__.parent, ".block.rx"),
    "RxBookmark": (__spec__.parent, ".block.rx"),
    "RxBookmarkBlock": (__spec__.parent, ".block.rx"),
    "RxBreadcrumbBlock": (__spec__.parent, ".block.rx"),
    "RxBulletListItem": (__spec__.parent, ".block.rx"),
    "RxBulletListItemBlock": (__spec__.parent, ".block.rx"),
    "RxCallout": (__spec__.parent, ".block.rx"),
    "RxCalloutBlock": (__spec__.parent, ".block.rx"),
    "RxCaptionExternalFile": (__spec__.parent, ".block.rx"),
    "RxCaptionExternalFileWithName": (__spec__.parent, ".block.rx"),
    "RxCaptionFile": (__spec__.parent, ".block.rx"),
    "RxCaptionFileWithName": (__spec__.parent, ".block.rx"),
    "RxCaptionHostedFile": (__spec__.parent, ".block.rx"),
    "RxCaptionHostedFileWithName": (__spec__.parent, ".block.rx"),
    "RxTableRow": (__spec__.parent, ".block.rx"),
    "RxTable": (__spec__.parent, ".block.rx"),
    "RxChildDatabaseBlock": (__spec__.parent, ".block.rx"),
    "RxChildPageBlock": (__spec__.parent, ".block.rx"),
    "RxCode": (__spec__.parent, ".block.rx"),
    "RxCodeBlock": (__spec__.parent, ".block.rx"),
    "RxColumnBlock": (__spec__.parent, ".block.rx"),
    "RxColumnListBlock": (__spec__.parent, ".block.rx"),
    "RxDividerBlock": (__spec__.parent, ".block.rx"),
    "RxEmbedBlock": (__spec__.parent, ".block.rx"),
    "RxEquationBlock": (__spec__.parent, ".block.rx"),
    "RxFileBlock": (__spec__.parent, ".block.rx"),
    "RxHeading": (__spec__.parent, ".block.rx"),
    "RxHeadingOneBlock": (__spec__.parent, ".block.rx"),
    "RxHeadingThreeBlock": (__spec__.parent, ".block.rx"),
    "RxHeadingTwoBlock": (__spec__.parent, ".block.rx"),
    "RxImageBlock": (__spec__.parent, ".block.rx"),
    "RxNumberedListItem": (__spec__.parent, ".block.rx"),
    "RxNumberedListItemBlock": (__spec__.parent, ".block.rx"),
    "RxOriginalSynced": (__spec__.parent, ".block.rx"),
    "RxParagraph": (__spec__.parent, ".block.rx"),
    "RxParagraphBlock": (__spec__.parent, ".block.rx"),
    "RxPdfBlock": (__spec__.parent, ".block.rx"),
    "RxQuote": (__spec__.parent, ".block.rx"),
    "RxQuoteBlock": (__spec__.parent, ".block.rx"),
    "RxSynced": (__spec__.parent, ".block.rx"),
    "RxSyncedBlock": (__spec__.parent, ".block.rx"),
    "RxTableBlock": (__spec__.parent, ".block.rx"),
    "RxTableContentBlock": (__spec__.parent, ".block.rx"),
    "RxTableRowBlock": (__spec__.parent, ".block.rx"),
    "RxToDo": (__spec__.parent, ".block.rx"),
    "RxToDoBlock": (__spec__.parent, ".block.rx"),
    "RxToggle": (__spec__.parent, ".block.rx"),
    "RxToggleBlock": (__spec__.parent, ".block.rx"),
    "RxUnsupportedBlock": (__spec__.parent, ".block.rx"),
    "RxVideoBlock": (__spec__.parent, ".block.rx"),
    "TxBlock": (__spec__.parent, ".block.tx"),
    "TxBookmark": (__spec__.parent, ".block.tx"),
    "TxBookmarkBlock": (__spec__.parent, ".block.tx"),
    "TxBreadcrumbBlock": (__spec__.parent, ".block.tx"),
    "TxBulletListItem": (__spec__.parent, ".block.tx"),
    "TxBulletListItemBlock": (__spec__.parent, ".block.tx"),
    "TxCallout": (__spec__.parent, ".block.tx"),
    "TxCalloutBlock": (__spec__.parent, ".block.tx"),
    "TxCaptionExternalFile": (__spec__.parent, ".block.tx"),
    "TxCaptionExternalFileWithName": (__spec__.parent, ".block.tx"),
    "TxCaptionFile": (__spec__.parent, ".block.tx"),
    "TxCaptionFileWithName": (__spec__.parent, ".block.tx"),
    "TxCaptionHostedFile": (__spec__.parent, ".block.tx"),
    "TxCaptionHostedFileWithName": (__spec__.parent, ".block.tx"),
    "TxTableRow": (__spec__.parent, ".block.tx"),
    "TxTable": (__spec__.parent, ".block.tx"),
    "TxCode": (__spec__.parent, ".block.tx"),
    "TxCodeBlock": (__spec__.parent, ".block.tx"),
    "TxColumnChildren": (__spec__.parent, ".block.tx"),
    "TxColumnBlock": (__spec__.parent, ".block.tx"),
    "TxColumnBlocks": (__spec__.parent, ".block.tx"),
    "TxColumnListBlock": (__spec__.parent, ".block.tx"),
    "TxDividerBlock": (__spec__.parent, ".block.tx"),
    "TxEmbedBlock": (__spec__.parent, ".block.tx"),
    "TxEquationBlock": (__spec__.parent, ".block.tx"),
    "TxFileBlock": (__spec__.parent, ".block.tx"),
    "TxHeading": (__spec__.parent, ".block.tx"),
    "TxHeadingOneBlock": (__spec__.parent, ".block.tx"),
    "TxHeadingThreeBlock": (__spec__.parent, ".block.tx"),
    "TxHeadingTwoBlock": (__spec__.parent, ".block.tx"),
    "TxImageBlock": (__spec__.parent, ".block.tx"),
    "TxNumberedListItem": (__spec__.parent, ".block.tx"),
    "TxNumberedListItemBlock": (__spec__.parent, ".block.tx"),
    "TxOriginalSynced": (__spec__.parent, ".block.tx"),
    "TxParagraph": (__spec__.parent, ".block.tx"),
    "TxParagraphBlock": (__spec__.parent, ".block.tx"),
    "TxPdfBlock": (__spec__.parent, ".block.tx"),
    "TxQuote": (__spec__.parent, ".block.tx"),
    "TxQuoteBlock": (__spec__.parent, ".block.tx"),
    "TxSynced": (__spec__.parent, ".block.tx"),
    "TxSyncedBlock": (__spec__.parent, ".block.tx"),
    "TxTableBlock": (__spec__.parent, ".block.tx"),
    "TxTableContentBlock": (__spec__.parent, ".block.tx"),
    "TxTableRowBlock": (__spec__.parent, ".block.tx"),
    "TxToDo": (__spec__.parent, ".block.tx"),
    "TxToDoBlock": (__spec__.parent, ".block.tx"),
    "TxToggle": (__spec__.parent, ".block.tx"),
    "TxToggleBlock": (__spec__.parent, ".block.tx"),
    "TxVideoBlock": (__spec__.parent, ".block.tx"),
    # property
    "PropertyType": (__spec__.parent, ".property.types"),
    "FormulaValueType": (__spec__.parent, ".property.types"),
    "RollupValueType": (__spec__.parent, ".property.types"),
    "NumberFormat": (__spec__.parent, ".property.types"),
    "RollupFunction": (__spec__.parent, ".property.types"),
    "StringFormulaValue": (__spec__.parent, ".property.common"),
    "NumberFormulaValue": (__spec__.parent, ".property.common"),
    "BooleanFormulaValue": (__spec__.parent, ".property.common"),
    "DateFormulaValue": (__spec__.parent, ".property.common"),
    "FormulaValue": (__spec__.parent, ".property.common"),
    # Property Objects
    "BaseOption": (__spec__.parent, ".property.rx"),
    "SelectOptions": (__spec__.parent, ".property.rx"),
    "Number": (__spec__.parent, ".property.rx"),
    "SyncRelation": (__spec__.parent, ".property.rx"),
    "DualRelation": (__spec__.parent, ".property.rx"),
    "SingleRelation": (__spec__.parent, ".property.rx"),
    "Relation": (__spec__.parent, ".property.rx"),
    "Rollup": (__spec__.parent, ".property.rx"),
    "StatusOptions": (__spec__.parent, ".property.rx"),
    "GroupOption": (__spec__.parent, ".property.rx"),
    # Property
    "Property": (__spec__.parent, ".property.rx"),
    "CheckboxProperty": (__spec__.parent, ".property.rx"),
    "CreatedByProperty": (__spec__.parent, ".property.rx"),
    "CreatedTimeProperty": (__spec__.parent, ".property.rx"),
    "DateProperty": (__spec__.parent, ".property.rx"),
    "EmailProperty": (__spec__.parent, ".property.rx"),
    "FilesProperty": (__spec__.parent, ".property.rx"),
    "FormulaProperty": (__spec__.parent, ".property.rx"),
    "LastEditedByProperty": (__spec__.parent, ".property.rx"),
    "LastEditedTimeProperty": (__spec__.parent, ".property.rx"),
    "MultiSelectProperty": (__spec__.parent, ".property.rx"),
    "NumberProperty": (__spec__.parent, ".property.rx"),
    "PeopleProperty": (__spec__.parent, ".property.rx"),
    "PhoneNumberProperty": (__spec__.parent, ".property.rx"),
    "RelationProperty": (__spec__.parent, ".property.rx"),
    "RichTextProperty": (__spec__.parent, ".property.rx"),
    "RollupProperty": (__spec__.parent, ".property.rx"),
    "SelectProperty": (__spec__.parent, ".property.rx"),
    "StatusProperty": (__spec__.parent, ".property.rx"),
    "TitleProperty": (__spec__.parent, ".property.rx"),
    "UrlProperty": (__spec__.parent, ".property.rx"),
    # Property Item
    "RxPaginatedTitlePropertyItem": (__spec__.parent, ".property.rx"),
    "RxPaginatedRichTextPropertyItem": (__spec__.parent, ".property.rx"),
    "RxPaginatedRelationPropertyItem": (__spec__.parent, ".property.rx"),
    "RxPaginatedPeoplePropertyItem": (__spec__.parent, ".property.rx"),
    "RxPaginatedPropertyItem": (__spec__.parent, ".property.rx"),
    "RxTitlePropertyItem": (__spec__.parent, ".property.rx"),
    "RxRichTextPropertyItem": (__spec__.parent, ".property.rx"),
    "RxRelationPropertyItem": (__spec__.parent, ".property.rx"),
    "RxPeoplePropertyItem": (__spec__.parent, ".property.rx"),
    "RxRollupPropertyItem": (__spec__.parent, ".property.rx"),
    "RxPropertyItem": (__spec__.parent, ".property.rx"),
    # Property values
    "ArrayRollupValue": (__spec__.parent, ".property.rx"),
    "DateRollupValue": (__spec__.parent, ".property.rx"),
    "IncompleteRollupValue": (__spec__.parent, ".property.rx"),
    "NumberRollupValue": (__spec__.parent, ".property.rx"),
    "UnsupportedRollupValue": (__spec__.parent, ".property.rx"),
    "RollupValue": (__spec__.parent, ".property.rx"),
    "UniqueIdValue": (__spec__.parent, ".property.rx"),
    "UnverifiedValue": (__spec__.parent, ".property.rx"),
    "VerifiedValue": (__spec__.parent, ".property.rx"),
    "VerificationValue": (__spec__.parent, ".property.rx"),
    "RxOptionValue": (__spec__.parent, ".property.rx"),
    "CreatedByPropertyValue": (__spec__.parent, ".property.rx"),
    "CreatedTimePropertyValue": (__spec__.parent, ".property.rx"),
    "LastEditedByPropertyValue": (__spec__.parent, ".property.rx"),
    "LastEditedTimePropertyValue": (__spec__.parent, ".property.rx"),
    "RollupPropertyValue": (__spec__.parent, ".property.rx"),
    "FormulaPropertyValue": (__spec__.parent, ".property.rx"),
    "UniqueIdPropertyValue": (__spec__.parent, ".property.rx"),
    "VerificationPropertyValue": (__spec__.parent, ".property.rx"),
    "RxCheckboxPropertyValue": (__spec__.parent, ".property.rx"),
    "RxDatePropertyValue": (__spec__.parent, ".property.rx"),
    "RxEmailPropertyValue": (__spec__.parent, ".property.rx"),
    "RxFilesPropertyValue": (__spec__.parent, ".property.rx"),
    "RxMultiSelectPropertyValue": (__spec__.parent, ".property.rx"),
    "RxNumberPropertyValue": (__spec__.parent, ".property.rx"),
    "RxPeoplePropertyValue": (__spec__.parent, ".property.rx"),
    "RxPhoneNumberPropertyValue": (__spec__.parent, ".property.rx"),
    "RxRelationPropertyValue": (__spec__.parent, ".property.rx"),
    "RxRichTextPropertyValue": (__spec__.parent, ".property.rx"),
    "RxSelectPropertyValue": (__spec__.parent, ".property.rx"),
    "RxStatusPropertyValue": (__spec__.parent, ".property.rx"),
    "RxTitlePropertyValue": (__spec__.parent, ".property.rx"),
    "RxUrlPropertyValue": (__spec__.parent, ".property.rx"),
    "RxPropertyValue": (__spec__.parent, ".property.rx"),
    "TxOptionValue": (__spec__.parent, ".property.tx"),
    "TxCheckboxPropertyValue": (__spec__.parent, ".property.tx"),
    "TxDatePropertyValue": (__spec__.parent, ".property.tx"),
    "TxEmailPropertyValue": (__spec__.parent, ".property.tx"),
    "TxFilesPropertyValue": (__spec__.parent, ".property.tx"),
    "TxMultiSelectPropertyValue": (__spec__.parent, ".property.tx"),
    "TxNumberPropertyValue": (__spec__.parent, ".property.tx"),
    "TxPeoplePropertyValue": (__spec__.parent, ".property.tx"),
    "TxPhoneNumberPropertyValue": (__spec__.parent, ".property.tx"),
    "TxRelationPropertyValue": (__spec__.parent, ".property.tx"),
    "TxRichTextPropertyValue": (__spec__.parent, ".property.tx"),
    "TxSelectPropertyValue": (__spec__.parent, ".property.tx"),
    "TxStatusPropertyValue": (__spec__.parent, ".property.tx"),
    "TxTitlePropertyValue": (__spec__.parent, ".property.tx"),
    "TxUrlPropertyValue": (__spec__.parent, ".property.tx"),
    "TxPropertyValue": (__spec__.parent, ".property.tx"),
    # Property schemas
    "NumberSchema": (__spec__.parent, ".property.tx"),
    "DualRelationSchema": (__spec__.parent, ".property.tx"),
    "SingleRelationSchema": (__spec__.parent, ".property.tx"),
    "RelationSchema": (__spec__.parent, ".property.tx"),
    "BaseOptionSchema": (__spec__.parent, ".property.tx"),
    "SelectOptionsSchema": (__spec__.parent, ".property.tx"),
    "RollupSchema": (__spec__.parent, ".property.tx"),
    "TitlePropertySchema": (__spec__.parent, ".property.tx"),
    "RichTextPropertySchema": (__spec__.parent, ".property.tx"),
    "NumberPropertySchema": (__spec__.parent, ".property.tx"),
    "SelectPropertySchema": (__spec__.parent, ".property.tx"),
    "MultiSelectPropertySchema": (__spec__.parent, ".property.tx"),
    "DatePropertySchema": (__spec__.parent, ".property.tx"),
    "PeoplePropertySchema": (__spec__.parent, ".property.tx"),
    "FilesPropertySchema": (__spec__.parent, ".property.tx"),
    "CheckboxPropertySchema": (__spec__.parent, ".property.tx"),
    "UrlPropertySchema": (__spec__.parent, ".property.tx"),
    "EmailPropertySchema": (__spec__.parent, ".property.tx"),
    "PhoneNumberPropertySchema": (__spec__.parent, ".property.tx"),
    "FormulaPropertySchema": (__spec__.parent, ".property.tx"),
    "RelationPropertySchema": (__spec__.parent, ".property.tx"),
    "RollupPropertySchema": (__spec__.parent, ".property.tx"),
    "CreatedTimePropertySchema": (__spec__.parent, ".property.tx"),
    "CreatedByPropertySchema": (__spec__.parent, ".property.tx"),
    "LastEditedTimePropertySchema": (__spec__.parent, ".property.tx"),
    "LastEditedByPropertySchema": (__spec__.parent, ".property.tx"),
    "PropertySchema": (__spec__.parent, ".property.tx"),
    # comments
    "RxComment": (__spec__.parent, ".comment"),
    "TxCommentWithParent": (__spec__.parent, ".comment"),
    "TxCommentWithDiscussionId": (__spec__.parent, ".comment"),
    # pages
    "RxPage": (__spec__.parent, ".page"),
    "TxPage": (__spec__.parent, ".page"),
    # databases
    "RxDatabase": (__spec__.parent, ".database"),
    "CreateDatabase": (__spec__.parent, ".database"),
    "UpdateDatabase": (__spec__.parent, ".database"),
    # Pagination
    "PaginatedItem": (__spec__.parent, ".query"),
    "PaginationType": (__spec__.parent, ".query"),
    "BlockPagination": (__spec__.parent, ".query"),
    "CommentPagination": (__spec__.parent, ".query"),
    "DatabasePagination": (__spec__.parent, ".query"),
    "PagePagination": (__spec__.parent, ".query"),
    "PageOrDatabasePagination": (__spec__.parent, ".query"),
    "PropertyItemPagination": (__spec__.parent, ".query"),
    "UserPagination": (__spec__.parent, ".query"),
    "TxPagination": (__spec__.parent, ".query"),
    # Sort
    "SortDirection": (__spec__.parent, ".query"),
    "PropertySort": (__spec__.parent, ".query"),
    "TimestampSort": (__spec__.parent, ".query"),
    "NotionSort": (__spec__.parent, ".query"),
    # Filters
    "CheckboxCondition": (__spec__.parent, ".query"),
    "DateCondition": (__spec__.parent, ".query"),
    "FilesCondition": (__spec__.parent, ".query"),
    "MultiSelectCondition": (__spec__.parent, ".query"),
    "NumberCondition": (__spec__.parent, ".query"),
    "PersonCondition": (__spec__.parent, ".query"),
    "RelationCondition": (__spec__.parent, ".query"),
    "RichTextCondition": (__spec__.parent, ".query"),
    "SelectCondition": (__spec__.parent, ".query"),
    "StatusCondition": (__spec__.parent, ".query"),
    "UniqueIdCondition": (__spec__.parent, ".query"),
    "FormulaCondition": (__spec__.parent, ".query"),
    "RollupCondition": (__spec__.parent, ".query"),
    "FilterCondition": (__spec__.parent, ".query"),
    "CheckboxFilter": (__spec__.parent, ".query"),
    "DateFilter": (__spec__.parent, ".query"),
    "FilesFilter": (__spec__.parent, ".query"),
    "FormulaFilter": (__spec__.parent, ".query"),
    "MultiSelectFilter": (__spec__.parent, ".query"),
    "NumberFilter": (__spec__.parent, ".query"),
    "PeopleFilter": (__spec__.parent, ".query"),
    "RelationFilter": (__spec__.parent, ".query"),
    "RichTextFilter": (__spec__.parent, ".query"),
    "RollupFilter": (__spec__.parent, ".query"),
    "SelectFilter": (__spec__.parent, ".query"),
    "StatusFilter": (__spec__.parent, ".query"),
    "UniqueIdFilter": (__spec__.parent, ".query"),
    "CreatedTimeFilter": (__spec__.parent, ".query"),
    "LastEditedTimeFilter": (__spec__.parent, ".query"),
    "AndPropertyFilter": (__spec__.parent, ".query"),
    "OrPropertyFilter": (__spec__.parent, ".query"),
    "PropertyFilter": (__spec__.parent, ".query"),
    "ObjectFilter": (__spec__.parent, ".query"),
}

__all__ = list(_dynamic_imports.keys())


def __getattr__(attr_name: str) -> object:
    dynamic_attr = _dynamic_imports.get(attr_name)
    if dynamic_attr is None:
        raise AttributeError(f"module '{__name__}' has no attribute '{attr_name}'")

    package, module_name = dynamic_attr
    resolved = set()

    while True:
        try:
            module = import_module(module_name, package=package)
            result = getattr(module, attr_name)

            if hasattr(result, "model_rebuild"):
                result.model_rebuild(force=True)

            globals()[attr_name] = result
            return result

        except PydanticUndefinedAnnotation as e:
            if e.name in resolved:
                raise RuntimeError(
                    f"Forward reference '{e.name}' could not be resolved "
                    f"while resolving '{attr_name}'"
                ) from e

            resolved.add(e.name)

            if e.name in _dynamic_imports:
                # Dynamically import the missing type
                dep_obj = __getattr__(e.name)

                # Inject into both this module and the model’s original module
                model_module = import_module(module_name, package=package)
                setattr(model_module, e.name, dep_obj)
                continue

            raise ImportError(
                f"Cannot resolve forward reference '{e.name}' for model '{attr_name}'"
            ) from e


def __dir__() -> list[str]:
    return list(__all__)


if TYPE_CHECKING:
    from .block.types import *
    from .comment import *
    from .database import *
    from .object import *
    from .page import *
    from .property.tx import *
    from .property.types import *
    from .query import *
    from .rich_text.types import *
    from .types import *
    from .block.common import (
        SyncedFrom,
        DuplicateSynced,
        TableOfContents,
    )
    from .block.rx import (
        ChildDatabase,
        ChildPage,
        RxBlock,
        RxBookmark,
        RxBookmarkBlock,
        RxBreadcrumbBlock,
        RxBulletListItem,
        RxBulletListItemBlock,
        RxCallout,
        RxCalloutBlock,
        RxCaptionExternalFile,
        RxCaptionExternalFileWithName,
        RxCaptionFile,
        RxCaptionFileWithName,
        RxCaptionHostedFile,
        RxCaptionHostedFileWithName,
        RxTableRow,
        RxTable,
        RxChildDatabaseBlock,
        RxChildPageBlock,
        RxCode,
        RxCodeBlock,
        RxColumnBlock,
        RxColumnListBlock,
        RxDividerBlock,
        RxEmbedBlock,
        RxEquationBlock,
        RxFileBlock,
        RxHeading,
        RxHeadingOneBlock,
        RxHeadingThreeBlock,
        RxHeadingTwoBlock,
        RxImageBlock,
        RxNumberedListItem,
        RxNumberedListItemBlock,
        RxOriginalSynced,
        RxParagraph,
        RxParagraphBlock,
        RxPdfBlock,
        RxQuote,
        RxQuoteBlock,
        RxSynced,
        RxSyncedBlock,
        RxTableBlock,
        RxTableContentBlock,
        RxTableRowBlock,
        RxToDo,
        RxToDoBlock,
        RxToggle,
        RxToggleBlock,
        RxUnsupportedBlock,
        RxVideoBlock,
    )
    from .block.tx import (
        TxBlock,
        TxBookmark,
        TxBookmarkBlock,
        TxBreadcrumbBlock,
        TxBulletListItem,
        TxBulletListItemBlock,
        TxCallout,
        TxCalloutBlock,
        TxCaptionExternalFile,
        TxCaptionExternalFileWithName,
        TxCaptionFile,
        TxCaptionFileWithName,
        TxCaptionHostedFile,
        TxCaptionHostedFileWithName,
        TxTableRow,
        TxTable,
        TxCode,
        TxCodeBlock,
        TxColumnChildren,
        TxColumnBlock,
        TxColumnBlocks,
        TxColumnListBlock,
        TxDividerBlock,
        TxEmbedBlock,
        TxEquationBlock,
        TxFileBlock,
        TxHeading,
        TxHeadingOneBlock,
        TxHeadingThreeBlock,
        TxHeadingTwoBlock,
        TxImageBlock,
        TxNumberedListItem,
        TxNumberedListItemBlock,
        TxOriginalSynced,
        TxParagraph,
        TxParagraphBlock,
        TxPdfBlock,
        TxQuote,
        TxQuoteBlock,
        TxSynced,
        TxSyncedBlock,
        TxTableBlock,
        TxTableContentBlock,
        TxTableRowBlock,
        TxToDo,
        TxToDoBlock,
        TxToggle,
        TxToggleBlock,
        TxVideoBlock,
    )

    from .emoji import (
        EmojiType,
        CustomEmojiObject,
        SingleEmoji,
        CustomEmoji,
        NotionEmoji,
    )
    from .file import (
        FileType,
        HostedFileObject,
        ExternalFileObject,
        HostedFile,
        HostedFileWithName,
        ExternalFile,
        ExternalFileWithName,
        NotionFile,
        NotionFileWithName,
    )

    from .parent import (
        ParentType,
        DatabaseParent,
        PageParent,
        BlockParent,
        WorkspaceParent,
        NotionParent,
    )
    from .property.common import (
        StringFormulaValue,
        NumberFormulaValue,
        BooleanFormulaValue,
        DateFormulaValue,
        FormulaValue,
    )
    from .property.rx import (
        # Property Objects
        BaseOption,
        SelectOptions,
        Number,
        SyncRelation,
        DualRelation,
        SingleRelation,
        Relation,
        Rollup,
        StatusOptions,
        GroupOption,
        # Property
        Property,
        CheckboxProperty,
        CreatedByProperty,
        CreatedTimeProperty,
        DateProperty,
        EmailProperty,
        FilesProperty,
        FormulaProperty,
        LastEditedByProperty,
        LastEditedTimeProperty,
        MultiSelectProperty,
        NumberProperty,
        PeopleProperty,
        PhoneNumberProperty,
        RelationProperty,
        RichTextProperty,
        RollupProperty,
        SelectProperty,
        StatusProperty,
        TitleProperty,
        UrlProperty,
        # Property Value
        ArrayRollupValue,
        DateRollupValue,
        IncompleteRollupValue,
        NumberRollupValue,
        UnsupportedRollupValue,
        RollupValue,
        UniqueIdValue,
        UnverifiedValue,
        VerifiedValue,
        VerificationValue,
        RxOptionValue,
        CreatedByPropertyValue,
        CreatedTimePropertyValue,
        LastEditedByPropertyValue,
        LastEditedTimePropertyValue,
        RollupPropertyValue,
        FormulaPropertyValue,
        UniqueIdPropertyValue,
        VerificationPropertyValue,
        RxCheckboxPropertyValue,
        RxDatePropertyValue,
        RxEmailPropertyValue,
        RxFilesPropertyValue,
        RxMultiSelectPropertyValue,
        RxNumberPropertyValue,
        RxPeoplePropertyValue,
        RxPhoneNumberPropertyValue,
        RxRelationPropertyValue,
        RxRichTextPropertyValue,
        RxSelectPropertyValue,
        RxStatusPropertyValue,
        RxTitlePropertyValue,
        RxUrlPropertyValue,
        RxPropertyValue,
        # Property Item
        RxPaginatedTitlePropertyItem,
        RxPaginatedRichTextPropertyItem,
        RxPaginatedRelationPropertyItem,
        RxPaginatedPeoplePropertyItem,
        RxPaginatedPropertyItem,
        RxTitlePropertyItem,
        RxRichTextPropertyItem,
        RxRelationPropertyItem,
        RxPeoplePropertyItem,
        RxRollupPropertyItem,
        RxPropertyItem,
    )

    from .rich_text.common import (
        Annotations,
        Text,
        Equation,
        DatabaseMention,
        DateMention,
        LinkPreviewMention,
        PageMention,
        TemplateMentionDate,
        TemplateMentionUser,
        TemplateMention,
    )
    from .rich_text.rx import (
        RxMention,
        RxTextRichText,
        RxEquationRichText,
        RxMentionRichText,
        RxUserMention,
        RxRichText,
    )
    from .rich_text.tx import (
        TxTextRichText,
        TxEquationRichText,
        TxMentionRichText,
        TxUserMention,
        TxMention,
        TxRichText,
    )
    from .user import (
        UserType,
        BotOwnerType,
        WorkspaceBotOwner,
        UserBotOwner,
        Bot,
        Person,
        PersonUser,
        BotUser,
        UserRef,
        BotOwner,
        NotionUser,
    )
